graph = {
genesOfInterest: [
"differential expression",
"mutation",
],
nodes: [
{id:"PLCE1",samples: ["","YA==",]},
{id:"PIK3CD",samples: ["QA==","",]},
{id:"ARAF",samples: ["gA==","",]},
{id:"MAPK3",samples: ["","",]},
{id:"MAPK1",samples: ["","",]},
{id:"RALA",samples: ["","",]},
{id:"SRC",samples: ["","",]},
{id:"FRS2",samples: ["QA==","QA==",]},
{id:"KRAS",samples: ["","oA==",]},
{id:"PIK3C3",samples: ["","",]},
],
links: [
{source:"PIK3C3", target:"PLCE1", type:"pp"},
{source:"KRAS", target:"PLCE1", type:"pp"},
{source:"FRS2", target:"SRC", type:"pp"},
{source:"ARAF", target:"MAPK1", type:"pp"},
{source:"KRAS", target:"ARAF", type:"pp"},
{source:"PLCE1", target:"KRAS", type:"pp"},
{source:"FRS2", target:"PIK3CD", type:"pp"},
{source:"ARAF", target:"KRAS", type:"pp"},
{source:"FRS2", target:"PIK3C3", type:"pp"},
{source:"FRS2", target:"MAPK3", type:"pp"},
{source:"MAPK1", target:"FRS2", type:"pp"},
{source:"MAPK3", target:"ARAF", type:"pp"},
{source:"RALA", target:"KRAS", type:"pp"},
{source:"PLCE1", target:"PIK3CD", type:"pp"},
{source:"PIK3CD", target:"PLCE1", type:"pp"},
{source:"SRC", target:"RALA", type:"pp"},
{source:"PIK3CD", target:"FRS2", type:"pp"},
],
conditions: [
"sample1",
"sample2",
"sample3",
],
}